---
- name: Check if k3s-uninstall.sh exists
  stat:
    path: /usr/local/bin/k3s-uninstall.sh
  register: uninstall_script

- name: Run k3s-uninstall.sh
  command: /usr/local/bin/k3s-uninstall.sh
  when: uninstall_script.stat.exists

- name: Clean up k3s directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s
