---
- name: Create K3s cluster
  hosts: all
  become: true
  vars_files:
    - vars.yaml
  vars:
    ansible_user: root

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600

    # K3s

    - name: Install K3s
      import_role:
        name: k3s
        tasks_from: install.yaml

    # Gateway API

    - name: Install Gateway API CRDs
      import_role:
        name: gateway_api

    # SSH

    - name: Configure users and SSH
      import_role:
        name: users

    - name: Install fail2ban dependencies
      apt:
        name:
          - python3
          - python3-pip
          - python3-systemd
          - fail2ban
        state: present

    - name: Write fail2ban jail config
      copy:
        dest: /etc/fail2ban/jail.d/cloud-config.local
        content: |
          [sshd]
          enabled = true
          backend = systemd
          banaction = iptables-multiport
        owner: root
        group: root
        mode: "0644"
      notify: Restart fail2ban

    - name: Enable and start fail2ban
      systemd:
        name: fail2ban
        enabled: true
        state: started

  handlers:
    - name: Restart fail2ban
      systemd:
        name: fail2ban
        state: restarted
