---
- name: Reinstall K3s
  hosts: all
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: Uninstall K3s
      import_role:
        name: k3s
        tasks_from: uninstall.yaml
    - name: Install K3s
      import_role:
        name: k3s
        tasks_from: install.yaml
    - name: Install Gateway API CRDs
      import_role:
        name: gateway_api
